### ISSUE TITLE
ofcourse you can use 32bit 7zp to unzip this (and winrar)

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [Ozymandias81/DNF2001-LeakOzyRepo#6]
where you got that idea from?

**Comment by Ozymandias81** [comment]
Not an "idea", since I use 7zip 64bit and had issues to open the pre-release on another laptop I have with WinXP, I thought that many 32bit users would had problems unzipping it. Just corrected the description, thanks.

**Comment by MyTDT-Mysoft** [comment]
i see... maybe you had antivirus installed or some other protector tool... that adds dlls on all processes... and that had a default addressing that was causing 7z on that to not have the contiguous address space it needs... (despite that it is a bug for 7z to require a huge 1gb linear buffer... i think winrar does not have this weakness anyway, and extracting from console with 7z also helps that... i guess that people that are still using 32bit (like me) would know such things by now and so yeah thats not a problem then)... but 7z itself is aware of the potential problem (altough normally is a problem when COMPRESSING not EXTRACTING), so odds is that for new versions it wont happen either.
